### ISSUE TITLE
Could not find folder to patch

### ISSUE THREAD

**Issue by SeniorYeehaw** [AntonioDePau/KHPCPatchManager#34]
**Describe the bug**
when i go to apply a patch it just doesn't work and shows the message "Could not find folder to patch" will place a screenshot

**To Reproduce**
no idea how, literally just downloaded it and it just has not acted right, tried moving the files into the kh folder its self, giving them its own folder and nothing

**Expected behavior**
expect it to just patch it and work first try

**Screenshots**
![image](https://user-images.githubusercontent.com/121360536/209450644-04991915-c03f-4871-816b-c465eef12dbd.png)

**Version used (please complete the following information):**
V1.2.0

**Affected games (please complete the following information):**
KH2 at the moment, not tried any others

**Formats involved (please complete the following information):**
not a clue currently

**Additional context**

**Comment by AntonioDePau** [comment]
> To Reproduce
no idea how, literally just downloaded it and it just has not acted right, tried moving the files into the kh folder its self, giving them its own folder and nothing

You're going to have to provide some more information on what's being done.
Please write the steps you are following until you see the error message, should be something along the lines of:

1. Downloaded <patch name> from <url to the patch>
2. Double-click on KHPCPatchManager.exe
3. Selected a different path to the EN folder for the game's installation (if applicable)
4. Select previously downloaded .kh2pcpatch file
5. Proceed to patch
6. Error message displays instead of patching

**Comment by SeniorYeehaw** [comment]
1. Downloaded from Github
2. Double click and run KHPC PATCH MANAGER
3. Select the patch
4. and displays this
![image](https://user-images.githubusercontent.com/121360536/209451333-43858a17-cf45-4573-bae6-24d864677485.png)

Does not ask me a path to the EN Folder

**Comment by AntonioDePau** [comment]
Okay then:

- Where did you install the game?
- Can you go to "C:\Program Files\Epic Games\KH_1.5_2.5\Image\en\" and take a screenshot of the folder's content, please?

**Comment by SeniorYeehaw** [comment]
it is installed on my F:drive which doesn't have epic game on it if that helps you 
![image](https://user-images.githubusercontent.com/121360536/209451490-e96e39cc-877e-4810-8f49-6298e2adf337.png)
![image](https://user-images.githubusercontent.com/121360536/209451495-1e35fbe9-0090-4d59-8c87-8d95ae670663.png)

**Comment by AntonioDePau** [comment]
That _may_ be the issue. Do you, by any chance, **still have** a "en" folder here, in the C drive?
> C:\Program Files\Epic Games\KH_1.5_2.5\Image\en

If it's empty, you may want to delete it so that the patcher detects it as missing and you can be prompted to provide a new path. Let me know if that works.

**Comment by SeniorYeehaw** [comment]
you are amazing dude!
that worked thank you so much
have a great one!

**Comment by AntonioDePau** [comment]
No problem!
Enjoy :)
