### ISSUE TITLE
Does not ask for game install folder

### ISSUE THREAD

**Issue by cheezedburger** [AntonioDePau/KHPCPatchManager#5]
When running the current version (1.1.2), the program does not ask to specify the game folder. It begins extracting the patch like I already specified the folder, even if I do the original drag n drop method instead of using the GUI. And no one seems to have this problem.

**Comment by AntonioDePau** [comment]
Hey, it should only ask for the game install folder if the following (default) directory does not exist:
C:\Program Files\Epic Games\KH_1.5_2.5\Image\en\

Do you have such directory on your PC?

Could you provide more information regarding this issue? Detailed steps to reproduce (from how you start the exe to when you encounter the issue), expected behaviour, actual behaviour (you have it described more or less, but more details might help me identify the issue).

Thanks!

**Comment by cheezedburger** [comment]
I do have this directory, however when I originally ran the program I was running it from the folder I keep other patches in so I don't lose track of where it is. Does the program auto-search for the directory? That information was unclear in the details of the previous versions. This issue is the same regardless of where I run the program and the result every time in that the game does not get patched.

**Comment by AntonioDePau** [comment]
Is your game not installed in that default folder? Where is it?

The game does not get patched? Are you getting an error? Can you share the details of the patch you are trying to apply?

**Comment by cheezedburger** [comment]
So as it turns out, I was wrong in thinking the patch did not apply.
I was trying to apply the Japanese Dub mod onto KH1 and thought it was not applying because I was viewing the cutscenes through the Theater to check if it was applying. I forgot that the Theater where you can view cutscenes were a separate part of the 1.5 + 2.5 collection and are not affected by mods. This was my mistake. Thank you for hearing me out and sorry for the worry.
